### ISSUE TITLE
A mod should be removed from the site

### ISSUE THREAD

**Issue by NoobKiller1919** [Legacy-Fabric/legacyfabric.net#16]
See #15 and [TooManyItem's original page](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272385-toomanyitems-the-inventory-editor-and-more-1-8).
TooManyItems does not adhere to the source project's license and should be removed from the site.

**Comment by HowardZHY** [comment]
Too Many Items is not open source

**Comment by HowardZHY** [comment]
the TMI here is a version made by me to be compatible with Legacy Fabric.
TMI's copyright still belongs to Marglyph (although he was missing for 7 years).
I respect Marglyph's copyright info and I can remove my distribute version if Marglyph wants.

**Comment by HowardZHY** [comment]
and the modlist is a Mod compatibility status tested by the community.

**Comment by NoobKiller1919** [comment]
> the TMI here is a version made by me to be compatible with Legacy Fabric. TMI's copyright still belongs to Marglyph (although he was missing for 7 years). I respect Marglyph's copyright and I can remove my distribute version if Marglyph wants.

Show respect with your actions

**Comment by HowardZHY** [comment]
It's 2022 now, it's copyright is actually 2011-2014.

**Comment by HowardZHY** [comment]
and you should blame websites like 9minecraft first. These websites are commercial so not for personal use and the things downloaded from there could contain malware.

**Comment by NoobKiller1919** [comment]
It seemed you knew nothing about what "2011~2014" actually means

**Comment by NoobKiller1919** [comment]
> and you should blame websites like 9minecraft first. These websites are commercial so not for personal use and the things downloaded from there could contain malware.

I wonder if legacyfabric.net is anything like 9minecraft, and what did you think when you compared them together?

**Comment by HowardZHY** [comment]
Legacyfabric is the developer's community, and the mods page is just a mod compatibility status tested by the community.

**Comment by NoobKiller1919** [comment]
> Legacyfabric is the developer's community, and the mods page is just a mod compatibility status tested by the community.

Should the page contain any mod that violate copyright laws?

**Comment by NoobKiller1919** [comment]
> Legacyfabric is the developer's community, and the mods page is just a mod compatibility status tested by the community.

Should the page contain any mod that potentially violates copyright laws?

**Comment by HowardZHY** [comment]
If you wanna talk about copyright laws, you'd better go and report third-party download websites that are full of advertisements first, TMI is free for Personal and Educational use.

**Comment by Wyvest** [comment]
> It's 2022 now, it's copyright is actually 2011-2014.

wait until 2114 for the copyright to expire :)

**Comment by MikhailTapio** [comment]
> If you wanna talk about copyright laws, you'd better go and report third-party download websites that are full of advertisements first, TMI is free for Personal and Educational use.

Ja, I'd reported those ones, and now it's legacyfabric's turn. If they have no proper reason for this, I'll consider posting another "report".

**Comment by HowardZHY** [comment]
> > If you wanna talk about copyright laws, you'd better go and report third-party download websites that are full of advertisements first, TMI is free for Personal and Educational use.
> 
> I'd reported those websites, then it's legacyfabric's turn. If legacyfabric neither removes the content in question nor provides a reasonable explanation, I'll consider reporting it as well.

https://github.com/Legacy-Fabric/legacyfabric.net/pull/17#issuecomment-1283851535

**Comment by NoobKiller1919** [comment]
> > > If you wanna talk about copyright laws, you'd better go and report third-party download websites that are full of advertisements first, TMI is free for Personal and Educational use.
> > 
> > 
> > I'd reported those websites, then it's legacyfabric's turn. If legacyfabric neither removes the content in question nor provides a reasonable explanation, I'll consider reporting it as well.
> 
> [#17 (comment)](https://github.com/Legacy-Fabric/legacyfabric.net/pull/17#issuecomment-1283851535)

If that's merged, ofc this will be closed.

**Comment by NoobKiller1919** [comment]
Hopefully this won't be the case next time

**Comment by Wyvest** [comment]
> I'm sure this will be close as completed soon.
> Yea, my creation, but still belongs to Marglyph.

that's not how it works lmao

**Comment by BleachDev** [comment]
The license on the official TMI page says:

`All of TooManyItems except for the small portion excerpted from the original Minecraft game is copyright 2011-2013 Marglyph. TooManyItems is free for personal use only. Do not redistribute TooManyItems, including in mod packs. Making YouTube videos using TMI is good though!`
The only real restriction is redistributing, Howards mod doesn't redistribute any part of TMI, it does contain classes from TMI but they're modified to be compatible with LF, and since there isn't any restrictions on using the source code there shouldn't be a problem.

**Comment by HowardZHY** [comment]
no, there are still many restrictions about TMI, like it shouldn't be included in any modpacks.
here's the copyright info from decompiled code:
public static final String COPYRIGHT = "Copyright 2011-2014 Marglyph. Free for personal or educational use only. Do not redistribute TooManyItems, including in mod packs, and do not use TooManyItems\' source code or graphics in your own mods."
so just remove TMI from LF website to avoid further arguments.

**Comment by NoobKiller1919** [comment]
> The license on the official TMI page says:
> 
> `All of TooManyItems except for the small portion excerpted from the original Minecraft game is copyright 2011-2013 Marglyph. TooManyItems is free for personal use only. Do not redistribute TooManyItems, including in mod packs. Making YouTube videos using TMI is good though!`
> 
> The only real restriction is redistributing, Howards mod doesn't redistribute any part of TMI, it does contain classes from TMI but they're modified to be compatible with LF, and since there isn't any restrictions on using the source code there shouldn't be a problem.

The TMI page did only mention "do not redistribute", but it did not say that this is "the only real restriction".
Until we can determine exactly what this license is, it should be considered an "ARR".
We usually consider an open source GitHub repository an "ARR" when it doesn't come with a license, not to mention that the TMI mod itself is closed source.
