### ISSUE TITLE
The website is down

### ISSUE THREAD

**Issue by GaucovyAero** [Legacy-Fabric/legacyfabric.net#45]
![image](https://github.com/user-attachments/assets/1300263c-ea5e-4919-9318-696d5ed05493)

![image](https://github.com/user-attachments/assets/fd7e5fc8-9f4f-4f0a-99dc-8124d8134114)

**Comment by BluCobalt** [comment]
Yeah, sorry. This is an issue with the server provider and it is currently out of our control to fix. I submitted a ticket like 20 minutes ago so hopefully they can resolve it soon.

**Comment by GaucovyAero** [comment]
Okay, thanks for the info :)
