### ISSUE TITLE
Typo in mod link & dead links

### ISSUE THREAD

**Issue by YetAnotherMcModder** [Legacy-Fabric/legacyfabric.net#7]
For the mod _**One Block At A Time**_ a typo was made in the mod link

Instead of this (in mods.js):
`"link": "https://modrinth.com/mod/onebloc",`

it should be:
`"link": "https://modrinth.com/mod/oneblock",`

The following mods modrinth pages are dead:
_**Fatal Blow Legacy Backport
No Enchantment Cap Legacy Backport
Durability Speed Legacy Backport
AnTitanic**_

(Quickly searched around for github pages, but couldn't find them)

**Comment by PseudoDistant** [comment]
Yea I deleted the Modrinth pages for all four of those. :/

**Comment by BluCobalt** [comment]
> For the mod _**One Block At A Time**_ a typo was made in the mod link
> 
> Instead of this (in mods.js):
> `"link": "https://modrinth.com/mod/onebloc",`
> 
> it should be:
> `"link": "https://modrinth.com/mod/oneblock",`
> 
> The following mods modrinth pages are dead:
> _**Fatal Blow Legacy Backport
> No Enchantment Cap Legacy Backport
> Durability Speed Legacy Backport
> AnTitanic**_
> 
> (Quickly searched around for github pages, but couldn't find them)

Feel free to pr the fixes for these
